# tmux 2.9+

set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",*:Tc"

# Add backtick as prefix, double tap to send
set-option -g prefix2 `
bind ` send-keys `

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf \; display "Config reloaded"

# Enable mouse mode (tmux 2.1+)
set -g mouse on

# Theme
set -g status-bg 'colour235'
set -g status-left-length '100'
set -g status 'on'
set -g status-right-length '100'
set -g status-justify 'centre'
setw -g window-status-separator '  '
set -g status-left '#[fg=colour232,bg=green]#{prefix_highlight}#[fg=green,bg=colour238,nobold,nounderscore,noitalics]#[fg=colour222,bg=colour238]  #S #[fg=colour238,bg=colour235,nobold,nounderscore,noitalics]'
set -g status-right '#[fg=colour235,bg=colour235,nobold,nounderscore,noitalics]#[fg=blue,bg=colour235] %r  %a  %Y #[fg=colour238,bg=colour235,nobold,nounderscore,noitalics]#[fg=colour222,bg=colour238] #(tmux-spotify-info) #[fg=green,bg=colour238,nobold,nounderscore,noitalics]#[fg=colour232,bg=green] '

setw -g window-status-format '#[fg=blue,bg=colour235,nobold,nounderscore,noitalics]#I:#W-'
setw -g window-status-current-format '#[fg=colour222]#I:#W#F'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @prefix_highlight_empty_prompt ' TMUX '
set -g @prefix_highlight_empty_attr 'fg=default,bg=green'
set -g @prefix_highlight_prefix_prompt 'WAIT'
set -g @prefix_highlight_copy_prompt 'COPY'
set -g @prefix_highlight_sync_prompt 'SYNC'
set -g @prefix_highlight_fg 'default'
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_show_sync_mode 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
